export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "#7f7665",
        "primary-container": "#a7a7a7",
        "secondary-container": "#fdd274",
        "surface-container": "#eeeeee",
        "tertiary-fixed-dim": "#b0c6ff",
        "on-surface": "#1a1c1c",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "on-error-container": "#93000a",
        secondary: "#795900",
        "inverse-surface": "#2f3131",
        "on-tertiary-fixed": "#001945",
        "secondary-fixed-dim": "#ebc165",
        "surface-dim": "#dadada",
        "on-tertiary-fixed-variant": "#2c457c",
        "surface-container-high": "#e8e8e8",
        "on-primary-container": "#3c3c3c",
        "on-surface-variant": "#4e4637",
        primary: "#5e5e5e",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f0f1f1",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#775800",
        "outline-variant": "#d1c5b2",
        "surface-bright": "#f9f9f9",
        "on-tertiary-container": "#203a71",
        "on-secondary-fixed-variant": "#5b4300",
        "surface-variant": "#e2e2e2",
        "surface-container-low": "#f3f3f4",
        "secondary-fixed": "#ffdf9e",
        background: "#f9f9f9",
        "inverse-primary": "#c6c6c6",
        "tertiary-fixed": "#d9e2ff",
        "error-container": "#ffdad6",
        "tertiary-container": "#8ea6e4",
        tertiary: "#455d96",
        "on-secondary-fixed": "#261a00",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5e5e5e",
        "on-background": "#1a1c1c",
        surface: "#f9f9f9",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#474747",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      scrollBehavior: {
        smooth: "smooth",
      },
    },
  },
  plugins: [],
};
